// <auto-generated />
namespace Proyecto_TPV.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class TPV02 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TPV02));
        
        string IMigrationMetadata.Id
        {
            get { return "201603031130323_TPV02"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
