// <auto-generated />
namespace Proyecto_TPV.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class TPV06 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TPV06));
        
        string IMigrationMetadata.Id
        {
            get { return "201603040908045_TPV06"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
